// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_open_source_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSnkP00Isw8Wytc6fp6ClSqB0tGFRXirQ',
    appId: '1:796049769419:android:7bd16c15beb3f842afac4e',
    messagingSenderId: '796049769419',
    projectId: 'esimply-live',
    storageBucket: 'esimply-live.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ZUg5sMRJ4iNtHmif9pfT1LNdSy5TwzI',
    appId: '1:796049769419:ios:b948e22982569fc3afac4e',
    messagingSenderId: '796049769419',
    projectId: 'esimply-live',
    storageBucket: 'esimply-live.firebasestorage.app',
    androidClientId: '796049769419-i2tukjpood5kbc1gmkc4ivonlr9346qu.apps.googleusercontent.com',
    iosClientId: '796049769419-14l7na91o751h5jb5ce5lq2o87ism18j.apps.googleusercontent.com',
    iosBundleId: 'com.esimply.esim',
  );

}